import { addDays, format } from 'date-fns'
import { czyZalegle } from '../../domain/ustaleniaGlosowe'
import type { ElementOgarniacza, ReferencjaZrodla } from '../../domain/elementyOgarniacza'
import type { KonfiguracjaKafelkaPulpitu } from '../../domain/typy'

export interface AlertPulpitu { id: string; tytul: string; opis?: string; severity: 'info' | 'warning' | 'critical'; termin?: string; typ: 'overdue' | 'asap' | 'near'; sourceRef: ReferencjaZrodla; createdAt: string }
export function rozwiazZakresKafelka(k: KonfiguracjaKafelkaPulpitu, data: Date) { const dni = k.zakresCzasu === 'today' ? 0 : k.zakresCzasu === '3d' ? 2 : k.zakresCzasu === '7d' ? 6 : 29; return { od: format(data, 'yyyy-MM-dd'), do: format(addDays(data, dni), 'yyyy-MM-dd') } }
export function sortujKafelki(kafelki: readonly KonfiguracjaKafelkaPulpitu[]) { return [...kafelki].filter((k) => k.widoczny).sort((a, b) => a.kolejnosc - b.kolejnosc || a.typ.localeCompare(b.typ, 'pl')) }
function termin(element: ElementOgarniacza) { return element.terminGraniczny ?? element.data }
export function elementyDlaKafelka(k: KonfiguracjaKafelkaPulpitu, elementy: readonly ElementOgarniacza[], data: Date) { const zakres = rozwiazZakresKafelka(k, data); const otwarte = elementy.filter((e) => e.status === 'otwarty'); const wynik = k.typ === 'pilne' ? otwarte.filter((e) => czyZalegle({ id: e.id, date: termin(e), time: e.godzina, priority: e.priorytet, status: e.status }, data) || e.priorytet === 'asap' || e.priorytet === 'pilny') : k.typ === 'zadania' ? otwarte.filter((e) => { const t = termin(e); return Boolean(t && t >= zakres.od && t <= zakres.do) }) : []; return wynik.sort((a,b) => (termin(a) ?? '9999').localeCompare(termin(b) ?? '9999') || a.tytul.localeCompare(b.tytul, 'pl')).slice(0, k.limit) }
export function alertyZadan(elementy: readonly ElementOgarniacza[], data: Date): AlertPulpitu[] { return elementy.filter((e) => e.status === 'otwarty' && e.referencjaZrodla).flatMap((e) => { const zalegle = czyZalegle({ id: e.id, date: termin(e), time: e.godzina, priority: e.priorytet, status: e.status }, data); const typ = zalegle ? 'overdue' : e.priorytet === 'asap' ? 'asap' : null; return typ && e.referencjaZrodla ? [{ id: `${e.id}-${typ}`, tytul: e.tytul, opis: zalegle ? 'Zaległe zadanie' : 'Wymaga działania ASAP', severity: zalegle ? 'critical' : 'warning', termin: termin(e), typ, sourceRef: e.referencjaZrodla, createdAt: e.createdAt }] : [] }) }
export function deduplikujAlerty(alerty: readonly AlertPulpitu[]) { return [...new Map(alerty.map((a) => [`${a.sourceRef.modul}:${a.sourceRef.encjaId}:${a.typ}`, a])).values()] }
export function rangujAlerty(alerty: readonly AlertPulpitu[]) { const wagi = { overdue: 3, asap: 2, near: 1 }; return [...alerty].sort((a,b) => wagi[b.typ] - wagi[a.typ] || (a.termin ?? '9999').localeCompare(b.termin ?? '9999') || a.tytul.localeCompare(b.tytul, 'pl') || a.id.localeCompare(b.id)) }