import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Bell, CalendarPlus, Car, ListTodo, NotebookPen, Pill, Receipt, Stethoscope } from 'lucide-react'
import { pobierzRepozytorium } from '../data/Repozytorium'
import { dzisiajIso, utworzMetadane } from '../domain/fabryki'
import { parserRegulowySzybkiegoDodawania, uporzadkujTypySzybkiegoDodawania } from '../domain/parserSzybkiegoDodawania'
import type { BlokCzasu, DaneSzybkiegoDodawania, Lek, NazwaModulu, Notatka, Pojazd, Przypomnienie, TypSzybkiegoDodawania, Wizyta, Wydatek } from '../domain/typy'
import { utworzZadanie } from '../services/ZadaniaService'
import { Komunikat, Modal, Znacznik } from '../components/Interfejs'
import { platforma } from '../platform/platforma'
import { useAplikacja } from './KontekstAplikacji'

const typy: { typ: TypSzybkiegoDodawania; etykieta: string; ikona: typeof ListTodo; modul?: NazwaModulu }[] = [
  { typ: 'zadanie', etykieta: 'Zadanie', ikona: ListTodo, modul: 'zadania' }, { typ: 'notatka', etykieta: 'Notatka', ikona: NotebookPen, modul: 'notatki' },
  { typ: 'wydarzenie', etykieta: 'Wydarzenie', ikona: CalendarPlus, modul: 'planer' }, { typ: 'przypomnienie', etykieta: 'Przypomnienie', ikona: Bell, modul: 'przypomnienia' },
  { typ: 'wizyta', etykieta: 'Wizyta', ikona: Stethoscope, modul: 'wizyty' }, { typ: 'lek', etykieta: 'Lek', ikona: Pill, modul: 'leki' },
  { typ: 'wydatek', etykieta: 'Wydatek', ikona: Receipt, modul: 'finanse' }, { typ: 'samochod', etykieta: 'Samochód', ikona: Car, modul: 'samochod' },
]

function koniecWydarzenia(data: string, godzina: string) {
  const koniec = new Date(`${data}T${godzina}:00`)
  koniec.setMinutes(koniec.getMinutes() + 60)
  const dwaZnaki = (wartosc: number) => String(wartosc).padStart(2, '0')
  return `${koniec.getFullYear()}-${dwaZnaki(koniec.getMonth() + 1)}-${dwaZnaki(koniec.getDate())}T${dwaZnaki(koniec.getHours())}:${dwaZnaki(koniec.getMinutes())}:00`
}

export function SzybkieDodawanie({ zamknij, moze, danePoczatkowe = {} }: { zamknij: () => void; moze: (modul: NazwaModulu, operacja?: 'odczyt' | 'edycja') => boolean; danePoczatkowe?: DaneSzybkiegoDodawania }) {
  const { ustawienia, zapiszUstawienia } = useAplikacja()
  const [typ, ustawTyp] = useState<TypSzybkiegoDodawania>(danePoczatkowe.typ ?? 'zadanie')
  const [tresc, ustawTresc] = useState(danePoczatkowe.tresc ?? ''); const [tytul, ustawTytul] = useState(danePoczatkowe.tytul ?? ''); const [data, ustawDate] = useState(''); const [godzina, ustawGodzine] = useState(''); const [kwota, ustawKwote] = useState(''); const [instrukcja, ustawInstrukcje] = useState(''); const [blad, ustawBlad] = useState(''); const [wiecej, ustawWiecej] = useState(false)
  const [nadpisane, ustawNadpisane] = useState({ typ: Boolean(danePoczatkowe.typ), tytul: Boolean(danePoczatkowe.tytul), data: false, godzina: false })
  const sugestia = useMemo(() => ustawienia.szybkieDodawanie.parserWlaczony ? parserRegulowySzybkiegoDodawania.parse(tresc, { referenceDate: new Date() }) : undefined, [tresc, ustawienia.szybkieDodawanie.parserWlaczony])
  const uporzadkowane = useMemo(() => uporzadkujTypySzybkiegoDodawania(ustawienia.szybkieDodawanie).map((wartosc) => typy.find((element) => element.typ === wartosc)!).filter((element) => !element.modul || moze(element.modul, 'edycja')), [moze, ustawienia.szybkieDodawanie])
  const bezposrednie = uporzadkowane.filter((element) => ustawienia.szybkieDodawanie.widoczneTypy.includes(element.typ)); const pozostale = uporzadkowane.filter((element) => !bezposrednie.includes(element))
  useEffect(() => { if (!sugestia) return; if (!nadpisane.typ) ustawTyp(sugestia.suggestedType); if (!nadpisane.tytul) ustawTytul(sugestia.cleanedTitle); if (!nadpisane.data) ustawDate(sugestia.suggestedDate ?? ''); if (!nadpisane.godzina) ustawGodzine(sugestia.suggestedTime ?? '') }, [sugestia, nadpisane])
  const wybierzTyp = (nowy: TypSzybkiegoDodawania) => { ustawTyp(nowy); ustawNadpisane((stan) => ({ ...stan, typ: true })) }
  const zapisz = async (zdarzenie: FormEvent) => { zdarzenie.preventDefault(); const nazwa = tytul.trim() || tresc.trim(); if (!nazwa) return ustawBlad('Wpisz treść elementu.')
    try { if (typ === 'zadanie') await pobierzRepozytorium('zadania').zapisz({ ...utworzZadanie({ tytul: nazwa, opis: tytul.trim() ? tresc.trim() : '', priorytet: ustawienia.zadania.domyslnyPriorytet, termin: data ? `${data}${godzina ? `T${godzina}:00` : ''}` : undefined }), ...(data ? { dataElementu: data, trybTerminuElementu: godzina ? 'o_godzinie' as const : 'koniec_dnia' as const, ...(godzina ? { godzinaElementu: godzina } : {}) } : {}) })
      if (typ === 'notatka') await pobierzRepozytorium('notatki').zapisz({ ...utworzMetadane(), tytul: nazwa.slice(0, 70), tresc: tresc.trim(), tagi: [], powiazania: [] } satisfies Notatka)
      if (typ === 'wydarzenie') { if (!data || !godzina) throw new Error('Wydarzenie wymaga daty i godziny.'); await pobierzRepozytorium('blokiCzasu').zapisz({ ...utworzMetadane(), tytul: nazwa, poczatek: `${data}T${godzina}:00`, koniec: koniecWydarzenia(data, godzina), typ: 'inne', elastycznosc: 'twardy', status: 'zaakceptowany' } satisfies BlokCzasu) }
      if (typ === 'przypomnienie') { if (!data || !godzina) throw new Error('Przypomnienie wymaga daty i godziny.'); await pobierzRepozytorium('przypomnienia').zapisz({ ...utworzMetadane(), tytul: nazwa, typ: 'absolutne', czas: `${data}T${godzina}:00`, priorytet: ustawienia.zadania.domyslnyPriorytet, stan: 'nowe', eskalacja: false } satisfies Przypomnienie) }
      if (typ === 'wizyta') await pobierzRepozytorium('wizyty').zapisz({ ...utworzMetadane(), nazwa, status: data ? 'umowiona' : 'do_umowienia', data: data || undefined, godzina: godzina || undefined, notatka: '', pytania: [], dokumentyIds: [], checklista: [] } satisfies Wizyta)
      if (typ === 'lek') await pobierzRepozytorium('leki').zapisz({ ...utworzMetadane(), nazwa, dawkaInstrukcja: instrukcja.trim() || 'Uzupełnij instrukcję użytkownika', godziny: godzina ? [godzina] : [], aktywny: true } satisfies Lek)
      if (typ === 'wydatek') { const liczba = Number(kwota.replace(',', '.')); if (!Number.isFinite(liczba) || liczba <= 0) throw new Error('Podaj prawidłową kwotę wydatku.'); await pobierzRepozytorium('wydatki').zapisz({ ...utworzMetadane(), opis: nazwa, kwota: liczba, data: data || dzisiajIso(), kategoria: 'Inne' } satisfies Wydatek) }
      if (typ === 'samochod') await pobierzRepozytorium('pojazdy').zapisz({ ...utworzMetadane(), nazwa, planowanySerwisData: data || undefined, planowanySerwisGodzina: data && godzina ? godzina : undefined, notatka: tresc.trim() || undefined } satisfies Pojazd)
      await zapiszUstawienia({ szybkieDodawanie: { ...ustawienia.szybkieDodawanie, licznikiUzyc: { ...ustawienia.szybkieDodawanie.licznikiUzyc, [typ]: ustawienia.szybkieDodawanie.licznikiUzyc[typ] + 1 } } }); await platforma.haptyka.sukces(); zamknij()
    } catch (przyczyna) { ustawBlad(przyczyna instanceof Error ? przyczyna.message : 'Nie udało się zapisać elementu.') } }
  return <Modal tytul="Szybkie dodawanie" opis="Wpisz naturalnie, sprawdź propozycję i zatwierdź zapis." zamknij={zamknij} szeroki><form className="formularz" onSubmit={zapisz}>{blad && <Komunikat typ="blad">{blad}</Komunikat>}<div className="wybor-typu">{bezposrednie.map((element) => { const Ikona = element.ikona; return <button type="button" key={element.typ} className={typ === element.typ ? 'wybor-typu__przycisk wybor-typu__przycisk--aktywny' : 'wybor-typu__przycisk'} onClick={() => wybierzTyp(element.typ)}><Ikona aria-hidden="true" />{element.etykieta}</button> })}{pozostale.length > 0 && <button type="button" className="wybor-typu__przycisk" onClick={() => ustawWiecej(!wiecej)}>Więcej</button>}{wiecej && pozostale.map((element) => <button type="button" key={element.typ} className="wybor-typu__przycisk" onClick={() => wybierzTyp(element.typ)}>{element.etykieta}</button>)}</div><label className="pole pole--pelne"><span>Wpis naturalny *</span><input autoFocus value={tresc} onChange={(e) => ustawTresc(e.target.value)} placeholder="np. spotkanie jutro 15:30" /></label>{sugestia && tresc && <div className="pole pole--pelne"><span>Propozycja parsera</span><div><Znacznik wariant="informacja">{sugestia.confidence} pewność</Znacznik>{sugestia.alternatives.length > 0 && <small> Alternatywa: {sugestia.alternatives[0]}</small>}</div></div>}<label className="pole pole--pelne"><span>Tytuł *</span><input value={tytul} onChange={(e) => { ustawTytul(e.target.value); ustawNadpisane((stan) => ({ ...stan, tytul: true })) }} /></label>{['zadanie', 'wydarzenie', 'przypomnienie', 'wizyta', 'wydatek'].includes(typ) && <label className="pole"><span>Data</span><input type="date" required={typ === 'wydarzenie' || typ === 'przypomnienie'} value={data} onChange={(e) => { ustawDate(e.target.value); ustawNadpisane((stan) => ({ ...stan, data: true })) }} /></label>}{['zadanie', 'wydarzenie', 'przypomnienie', 'wizyta', 'lek'].includes(typ) && <label className="pole"><span>Godzina</span><input type="time" required={typ === 'wydarzenie' || typ === 'przypomnienie'} value={godzina} onChange={(e) => { ustawGodzine(e.target.value); ustawNadpisane((stan) => ({ ...stan, godzina: true })) }} /></label>}{typ === 'lek' && <label className="pole pole--pelne"><span>Instrukcja</span><input value={instrukcja} onChange={(e) => ustawInstrukcje(e.target.value)} placeholder="np. zgodnie z zaleceniem" /></label>}{typ === 'wydatek' && <label className="pole"><span>Kwota *</span><input type="number" min="0.01" step="0.01" value={kwota} onChange={(e) => ustawKwote(e.target.value)} /></label>}<div className="akcje-formularza pole--pelne"><button type="button" className="przycisk przycisk--drugorzedny" onClick={zamknij}>Anuluj</button><button type="submit" className="przycisk przycisk--glowny">Zapisz</button></div></form></Modal>
}
